### ISSUE TITLE
Should the default downloads folder be /overrides/mods ?

### ISSUE THREAD

**Issue by quat1024** [Nincraft/ModPackDownloader#50]
By default, CurseForge pack downloads have `manifest.json` next to an `overrides` folder. Inside `overrides` is a `mods` folder, containing all of the non-Curse mods.

If I place ModPackDownloader next to `manifest.json` and run it, it creates a separate `mods` folder *outside* of the `overrides` folder, and I have to manually merge MPD's mods folder with Curse's mods folder.

It would be nice if the default mods directory was `overrides/mods`, so all the mods end up in the same place.

**Comment by Nincodedo** [comment]
The thought was that the user would move everything out of the overrides folder into the folder with the manifest.json since that's kinda how the Curse launcher works. The modpack instance isn't inside the overrides folder.

Would it be better to have the default mods directory be `overrides/mods` or should MPD move everything from the overrides folder into the current folder?
